#!/usr/bin/env sh
# 由 git commit 和 git merge 调用
# 可以使用 git commit --no-verify 绕过

. "$(dirname -- "$0")/_/husky.sh"

#--no-install 参数表示强制npx使用项目中node_modules目录中的commitlint包
npx --no-install commitlint --edit $1